import Navbar from '@/components/Navbar'
import './globals.css'
import { Roboto_Mono, Space_Grotesk } from 'next/font/google'

 const spaceGrotesk = Space_Grotesk({
  subsets: ['latin']
})
 const robotoMono = Roboto_Mono({
  subsets: ['latin'],
  display: 'swap',
});
export const metadata = {
  title: 'TS Mentor Practice',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={spaceGrotesk.className}>
        <div className='grid place-content-center w-full min-h-screen bg-[#141c2f]'>
        <div className='sm:w-[500px] md:w-[600px] lg:w-[700px] grid gap-2'>
        <Navbar />
        {children}
        </div>
        </div>
      </body>
    </html>
  )
}
